### ISSUE TITLE
Uncaught TypeError: exists is not a function

### ISSUE THREAD

**Issue by uCloudCastle** [magiclen/node-magiccrypt#3]
use in vue project, get this Error:

bindings.js:158 Uncaught TypeError: exists is not a function
    at Function.getRoot (bindings.js:158)
    at bindings (bindings.js:60)
    at Object../node_modules/mhash/index.js (index.js:1)
    at __webpack_require__ (bootstrap:724)

**Comment by magiclen** [comment]
This is a back-end library based on [Node.js](https://nodejs.org/en/) framework. You cannot use it at front-end development. Btw, there are no solutions for MagicCrypt on browsers currently.

**Comment by uCloudCastle** [comment]
Thanks for the reply and have a nice day!
